spring:
  servlet:
    mime-mapping:
      mp4: video/mp4
      webm: video/webm
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
     host: smtp.gmail.com
     port: 587
     username: apkdhina@gmail.com
     password: jrle ydzn nzak rvod
     properties: 
       mail: 
         smtp:
           auth: true
           starttls:
             enable: true
  cache:
    caffeine:
      spec: expireAfterWrite=1h,maximumSize=1000
  
  mvc:
    pathmatch:
       matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://localhost:5432/realtors
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 600000
      pool-name: RealtorsHikariPool
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration  
  # optional: log SQL queries
  jdbc:
    template:
      fetch-size: 50

  web:
    resources:
      add-mappings: true

server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  servlet:
    context-path: /

app:
  backend:
    base-url: http://127.0.0.1:8080
  frontend:
    base-url: http://127.0.0.1:5173

logging:
  file:
    name: logs/application.log
  level:
    root: ERROR
    com.realtors: DEBUG 
    com.realitor.common.util.JsonAwareRowMapper: INFO
    org.springframework.web.servlet.resource.ResourceHttpRequestHandler: OFF
    org.springframework.jdbc.core.BeanPropertyRowMapper: WARN

jwt:
  secret: "ThisIsASecretKeyForJWTsChangeMe1234567890"  # use env var in production
  expiration-ms: 86400000
  refreshExpirationMs: 604800000

file:
  upload-dir: D:\temp\app-images\uploads
  temp-dir: D:\temp\